### ISSUE TITLE
Monster Hunter Double Cross [0004000000197100]

### ISSUE THREAD

**Issue by eve2ptp** [Lime3DS/compatibility-list#10]
### Prerequisites

- [X] I have checked there is no currently open report for this game. (An updated report can be made for games with previously closed reports).
- [X] I have read through the contribution guide [here](https://github.com/Lime3DS/compatibility-list/blob/master/CONTRIBUTING.md) from start to finish.
- [X] I have played through this game from start to finish only using official releases of the Lime3DS emulator.
- [X] The OpenGL renderer was used for my entire playthrough.

### Rating

Okay

### Description

Game Version: `1.4`

Description: `The game's frame rate drops intermittently from 60 (fps mod) to 52, regardless of whether OpenGL or Vulkan is used.`

### Lime3DS Version

2110

### System Configuration

CPU: 13600K
GPU/Driver: RTX 4070Super
RAM: 64G
OS: Win10 x64 22H2

**Comment by OpenSauce04** [comment]
This compatibility report doesn't seem to mention anything to do with graphical glitches or stability, which is the purpose of this report. Performance isn't typically a considered factor, as it varies depending on each device. Did you read the submission guide as mentioned in the template?

**Comment by eve2ptp** [comment]
Okay, but this is the only game that always has this intermittent frame rate drop, regardless of the computer's high or low configuration
