### ISSUE TITLE
KINGDOM HEARTS 3D [000400000008D300]

### ISSUE THREAD

**Issue by zcraftelite9495** [Lime3DS/compatibility-list#11]
### Prerequisites

- [X] I have checked there is no currently open report for this game. (An updated report can be made for games with previously closed reports).
- [X] I have read through the contribution guide [here](https://github.com/Lime3DS/compatibility-list/blob/master/CONTRIBUTING.md) from start to finish.
- [X] I have played through this game from start to finish only using official releases of the Lime3DS emulator.
- [X] The OpenGL renderer was used for my entire playthrough.

### Rating

Okay

### Description

Plays well (works best with controller) when using a compatable OpenGL renderer. Compatibility for this software has been deemed "WONT BOOT" in the past, however that information is now rendered incorrect.

### Lime3DS Version

2115

### System Configuration

CPU: Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz, 2701 Mhz, 2 Core(s), 4 Logical Processor(s)
GPU/Driver: Intel Integrated Graphics
RAM: 7.89 GB Physical, 19.4 GB Virtual
OS: Microsoft Windows 11 Pro 10.0.22631 Build 22631

**Comment by OpenSauce04** [comment]
I have a copy of DDD, so I'll get around verifying this myself

**Comment by MontyJack2020** [comment]
I can collaborate this report.

I would rate this as: Great

Description
I was able to play through the while game using OpenGL - it always boots up fine so the current label of Won't boot is incorrect. I played at 2x and 3x resolution and experienced little to no stutters.

Lime3DS Version
2117.1

System Configuration
CPU: AMD Ryzen 7 PRO 3700 8 Core processor 3.60 GHz
GPU/Driver: NVIDIA GeForce GT 1030
RAM: 32GB
OS: Microsoft Windows 10 22H2 19045.2965

**Comment by OpenSauce04** [comment]
@zcraftelite9495 what issues made you initially choose your rating as "Okay"?

**Comment by zcraftelite9495** [comment]
I found out this was due to an old version of OpenGL, but during some scenes the polygons were glitching out. I will be updating my rating to Great!

**Comment by OpenSauce04** [comment]
Closed by 0d7f51440a4a548444dff2d44a532d8c70f15a22
