### ISSUE TITLE
Thor: God of Thunder

### ISSUE THREAD

**Issue by KingSoma197** [Lime3DS/compatibility-list#13]
### Prerequisites

- [X] I have checked there is no currently open report for this game. (An updated report can be made for games with previously closed reports).
- [X] I have read through the contribution guide [here](https://github.com/Lime3DS/compatibility-list/blob/master/CONTRIBUTING.md) from start to finish.
- [X] I have played through this game from start to finish only using official releases of the Lime3DS emulator.
- [X] The OpenGL renderer was used for my entire playthrough.

### Rating

Bad

### Description

game has problems with character graphics, otherwise it works perfectly 

### Lime3DS Version

2116

### System Configuration

CPU:865
GPU/Driver:adreno650
RAM:6
OS:Android

**Comment by OpenSauce04** [comment]
Please attach the game ID to the title
