### ISSUE TITLE
3DS MENU[000400300000A902]

### ISSUE THREAD

**Issue by MygoathubID** [Lime3DS/compatibility-list#17]
### Prerequisites

- [x] I have checked there is no currently open report for this game. (An updated report can be made for games with previously closed reports).
- [X] I have read through the contribution guide [here](https://github.com/Lime3DS/compatibility-list/blob/master/CONTRIBUTING.md) from start to finish.
- [X] I have played through this game from start to finish only using official releases of the Lime3DS emulator.
- [X] The OpenGL renderer was used for my entire playthrough.

### Rating

Great

### Description

I am using 3DS Emulator so good. But there's a problem. I can't slot a Game card on Home Menu , CAM does not work. 
And I can't connect to internet. How do I solve this?

### Lime3DS Version

2118

### System Configuration

CPU:Apple M1
GPU/Driver:I Don't Know
RAM:I Don't Know
OS:MacOS 14.5 Sonoma

**Comment by OpenSauce04** [comment]
This isn't where you make bug reports. Use the main emulator repository instead.
