### ISSUE TITLE
Omega Ruby 

### ISSUE THREAD

**Issue by fruity-fkf** [Lime3DS/compatibility-list#18]
### Prerequisites

- [X] I have checked there is no currently open report for this game. (An updated report can be made for games with previously closed reports).
- [X] I have read through the contribution guide [here](https://github.com/Lime3DS/compatibility-list/blob/master/CONTRIBUTING.md) from start to finish.
- [X] I have played through this game from start to finish only using official releases of the Lime3DS emulator.
- [X] The OpenGL renderer was used for my entire playthrough.

### Rating

Great

### Description

The game Omeaga Ruby ran perfectly well except for a couple of glitches during the begining cutscene which don't go away for some reason regardless of the hardware

### Lime3DS Version

2188

### System Configuration

CPU:I5-8350U and Ryzen 3 3200g
GPU/Driver:Latest ones available on the arch repositories
RAM:16GB for the 3200G and 8 GB for the i5
OS:Arch linux

**Comment by OpenSauce04** [comment]
Please use the correct title format and provide a more in-depth description of the issues you faced
