### ISSUE TITLE
about miitopia

### ISSUE THREAD

**Issue by rexdesmith** [Lime3DS/compatibility-list#20]
### Prerequisites

- [X] I have checked there is no currently open report for this game. (An updated report can be made for games with previously closed reports).
- [X] I have read through the contribution guide [here](https://github.com/Lime3DS/compatibility-list/blob/master/CONTRIBUTING.md) from start to finish.
- [X] I have played through this game from start to finish only using official releases of the Lime3DS emulator.
- [X] The OpenGL renderer was used for my entire playthrough.

### Rating

--Select One--

### Description

the game is working perfectly without any issues, 
![20241020_084014](https://github.com/user-attachments/assets/b561e500-16de-46b7-bbb6-91e45d08a920)

### Lime3DS Version

2118.2

### System Configuration

CPU:11th gen intel (r) core (tm) i3-1125g4 @ 2.00 hz
GPU/Driver: intel (r) uhd graphics
RAM: 4
OS:22631.4317
![20241020_083936](https://github.com/user-attachments/assets/0b67e5ca-89d0-4784-9989-edca67a709c4)

**Comment by OpenSauce04** [comment]
Please follow the format correctly and read the submission guide if you haven't already
