### ISSUE TITLE
Pokémon Omega Ruby [000400000011C400]

### ISSUE THREAD

**Issue by WadyJorge** [Lime3DS/compatibility-list#3]
### Prerequisites

- [X] I have checked there is no currently open report for this game. (An updated report can be made for games with previously closed reports).
- [X] I have read through the contribution guide [here](https://github.com/Lime3DS/compatibility-list/blob/master/CONTRIBUTING.md) from start to finish.
- [X] I have played through this game from start to finish only using official releases of the Lime3DS emulator.
- [x] The OpenGL renderer was used for my entire playthrough.

### Rating

Okay

### Description

The game functions with major graphical or audio glitches but is still playable from beginning to end. I played more than 50% of the game and I can see that it is at least "Okay". Consistent performance. Some graphical bugs but nothing that ruins the gameplay. I played using the Vulkan API. 

### Lime3DS Version

2112

### System Configuration

CPU: AMD Ryzen 7 5800X3D
GPU/Driver: ASUS TUF RTX 4070 Super
RAM: Asgard Bragi 32GB (3800Mhz)
OS: Windows 11 Pro (23H2)

**Comment by OpenSauce04** [comment]
Please write a real description for your report. Simply copying the description of the 'Okay' rating does not qualify. Please describe your experience during the playthrough alongside describing the issues you experienced which lead to your rating of 'Okay'

Additionally, 2114.1 only released about an hour ago, so it is not possible that you have completed a playthrough on this version. You are either missing versions in the report or you have not completed a full playthrough
