### ISSUE TITLE
3D Classics Excitebike [0004000000054300]

### ISSUE THREAD

**Issue by TheRealWario** [Lime3DS/compatibility-list#4]
### Prerequisites

- [X] I have checked there is no currently open report for this game. (An updated report can be made for games with previously closed reports).
- [X] I have read through the contribution guide [here](https://github.com/Lime3DS/compatibility-list/blob/master/CONTRIBUTING.md) from start to finish.
- [x] I have played through this game from start to finish only using official releases of the Lime3DS emulator.
- [X] The OpenGL renderer was used for my entire playthrough.

### Rating

Perfect

### Description

The game runs as it should. Leaving the texture sampling as game controlled made the game look identical to console. The track maker works, audio is perfect, all checks out.

### Lime3DS Version

2114.1

### System Configuration

CPU: AMD Ryzen 5 5600H
GPU/Driver: NVIDIA GTX 1650
RAM: 24GB
OS: Windows 11 Home 23H2

**Comment by drewbyhk** [comment]
Can confirm that 3D Classics: Excitebike runs perfectly as described above.
