### ISSUE TITLE
Ocarina of Time 3D

### ISSUE THREAD

**Issue by rayplay70** [Lime3DS/compatibility-list#5]
### Prerequisites

- [X] I have checked there is no currently open report for this game. (An updated report can be made for games with previously closed reports).
- [X] I have read through the contribution guide [here](https://github.com/Lime3DS/compatibility-list/blob/master/CONTRIBUTING.md) from start to finish.
- [X] I have played through this game from start to finish only using official releases of the Lime3DS emulator.
- [X] The OpenGL renderer was used for my entire playthrough.

### Rating

Perfect

### Description

genial

### Lime3DS Version

2114.1

### System Configuration

CPU:Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz   3.20 GHz
GPU/Driver:Intel
RAM:20 GB
OS:Windows 11

**Comment by OpenSauce04** [comment]
The description and game title have not been filled out correctly. Please refer to the submission guide and open a new report
