### ISSUE TITLE
Animal Crossing: New Leaf [0004000000086400]

### ISSUE THREAD

**Issue by OpenSauce04** [Lime3DS/compatibility-list#9]
### Prerequisites

- [X] I have checked there is no currently open report for this game. (An updated report can be made for games with previously closed reports).
- [x] I have read through the contribution guide [here](https://github.com/Lime3DS/compatibility-list/blob/master/CONTRIBUTING.md) from start to finish.
- [X] I have played through this game from start to finish only using official releases of the Lime3DS emulator.
- [X] The OpenGL renderer was used for my entire playthrough.

### Rating

Perfect

### Description

There isn't really an "end" to Animal Crossing games, so I can't say anything for definite, however I have played this game for an extensive period of time and have failed to notice a single graphical glitch or other issue of any description

### Lime3DS Version

<=2115

### System Configuration

CPU: Intel Xeon E5-2680 v4
GPU/Driver: NVIDIA GeForce RTX 3060 Ti
RAM: 32GB
OS: Gentoo Linux

**Comment by zcraftelite9495** [comment]
Can confirm personally that Animal Crossing does not end, and works perfectly as described on this post!
